/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package GUI;

import Controller.Controller;
import java.time.LocalDate;
import java.util.List;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import model.Organizator;
import model.TipZurke;
import model.Zurka;

/**
 *
 * @author user
 */
public class Dodaj extends javax.swing.JDialog {

    /**
     * Creates new form Dodaj
     */
     private MainForma gf = new MainForma();
    Controller kontroler;
    Zurka zurkaZaIzmenu;
    public Dodaj(java.awt.Frame parent, boolean modal, Zurka zurkaZaIzmenu) {
        super(parent, modal);
        initComponents();
        this.gf = (MainForma) parent;
        kontroler=Controller.getInstance();
        popuniComboBoxOrganizatorima();
        
        if(zurkaZaIzmenu!=null){
            this.zurkaZaIzmenu=zurkaZaIzmenu;
            jTextFieldNaziv.setText(zurkaZaIzmenu.getNaziv());
            jTextFieldLokacija.setText(zurkaZaIzmenu.getLokacija());
            jTextFieldBrojGostiju.setText(String.valueOf(zurkaZaIzmenu.getBrojGostiju()));
            jTextFieldBudzet.setText(String.valueOf(zurkaZaIzmenu.getBudzet()));
            jComboBoxOrganizator.setSelectedItem(zurkaZaIzmenu.getOrganizator());
            jComboBoxTip.setSelectedItem(zurkaZaIzmenu.getTip());
            
            jButtonSave.setVisible(false);
            
        }
        else jButtonIzmeni.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextFieldNaziv = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButtonCancel = new javax.swing.JButton();
        jComboBoxOrganizator = new javax.swing.JComboBox<>();
        jButtonIzmeni = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldLokacija = new javax.swing.JTextField();
        jTextFieldBudzet = new javax.swing.JTextField();
        jComboBoxTip = new javax.swing.JComboBox<>();
        jTextFieldBrojGostiju = new javax.swing.JTextField();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jButtonSave = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Naziv: ");

        jLabel2.setText("Organizator:");

        jLabel3.setText("Datum:");

        jLabel4.setText("Tip:");

        jLabel5.setText("Lokacija:");

        jButtonCancel.setText("Cancel");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        jComboBoxOrganizator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxOrganizatorActionPerformed(evt);
            }
        });

        jButtonIzmeni.setText("Izmeni");
        jButtonIzmeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIzmeniActionPerformed(evt);
            }
        });

        jLabel6.setText("Broj Gostiju:");

        jLabel7.setText("Budzet:");

        jComboBoxTip.setModel(new DefaultComboBoxModel(model.TipZurke.values())
        );
        jComboBoxTip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTipActionPerformed(evt);
            }
        });

        jButtonSave.setText("Save");
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonCancel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 514, Short.MAX_VALUE)
                        .addComponent(jButtonIzmeni)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonSave)
                        .addGap(10, 10, 10))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldNaziv)
                            .addComponent(jComboBoxOrganizator, 0, 240, Short.MAX_VALUE)
                            .addComponent(jTextFieldLokacija)
                            .addComponent(jTextFieldBudzet, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jComboBoxTip, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldBrojGostiju)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBoxOrganizator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jComboBoxTip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldLokacija, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextFieldBrojGostiju, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextFieldBudzet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCancel)
                    .addComponent(jButtonIzmeni)
                    .addComponent(jButtonSave))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonCancelActionPerformed

    private void jComboBoxOrganizatorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxOrganizatorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxOrganizatorActionPerformed

    private void jButtonIzmeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIzmeniActionPerformed
       String naziv = jTextFieldNaziv.getText();
       Organizator org = (Organizator) jComboBoxOrganizator.getSelectedItem();
       TipZurke tip = (TipZurke) jComboBoxTip.getSelectedItem();
   java.util.Date date = jDateChooser1.getDate();  // jDateChooser umesto jCalendar
    LocalDate datum = date.toInstant().atZone(java.time.ZoneId.systemDefault()).toLocalDate();
    
    // Preuzimanje drugih vrednosti (lokacija, broj gostiju, budžet)
    String lokacija = jTextFieldLokacija.getText();
    int brojGostiju = Integer.parseInt(jTextFieldBrojGostiju.getText()); // Pretpostavljamo da je unos broj
    double budzet = Double.parseDouble(jTextFieldBudzet.getText()); // Pretpostavljamo da je unos broj
    
    // Kreiranje nove žurke
    
    zurkaZaIzmenu.setNaziv(naziv);
     zurkaZaIzmenu.setOrganizator(org);
      zurkaZaIzmenu.setBrojGostiju(brojGostiju);
       zurkaZaIzmenu.setBudzet(budzet);
        zurkaZaIzmenu.setDatum(datum);
         zurkaZaIzmenu.setTip(tip);
        gf.osveziTabelu();
        this.dispose();
    }//GEN-LAST:event_jButtonIzmeniActionPerformed

    private void jComboBoxTipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTipActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxTipActionPerformed

    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed
String naziv = jTextFieldNaziv.getText();
       Organizator org = (Organizator) jComboBoxOrganizator.getSelectedItem();
       TipZurke tip = (TipZurke) jComboBoxTip.getSelectedItem();
   java.util.Date date = jDateChooser1.getDate();  // jDateChooser umesto jCalendar
    LocalDate datum = date.toInstant().atZone(java.time.ZoneId.systemDefault()).toLocalDate();
    
    // Preuzimanje drugih vrednosti (lokacija, broj gostiju, budžet)
    String lokacija = jTextFieldLokacija.getText();
    int brojGostiju = Integer.parseInt(jTextFieldBrojGostiju.getText()); // Pretpostavljamo da je unos broj
    double budzet = Double.parseDouble(jTextFieldBudzet.getText()); // Pretpostavljamo da je unos broj
    
    // Kreiranje nove žurke
    Zurka zurka = new Zurka(naziv, org, tip, datum, lokacija, brojGostiju, budzet);
       
       kontroler.dodajZurku(zurka);
       gf.osveziTabelu();
       this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dodaj.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dodaj.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dodaj.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dodaj.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Dodaj dialog = new Dodaj(new javax.swing.JFrame(), true, null );
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonIzmeni;
    private javax.swing.JButton jButtonSave;
    private javax.swing.JComboBox<Organizator> jComboBoxOrganizator;
    private javax.swing.JComboBox<String> jComboBoxTip;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jTextFieldBrojGostiju;
    private javax.swing.JTextField jTextFieldBudzet;
    private javax.swing.JTextField jTextFieldLokacija;
    private javax.swing.JTextField jTextFieldNaziv;
    // End of variables declaration//GEN-END:variables

    private void popuniComboBoxOrganizatorima() {
        jComboBoxOrganizator.removeAllItems();
        List<Organizator> organizatori = kontroler.getListaOrganizatora();
        for (Organizator organizator : organizatori) {
                jComboBoxOrganizator.addItem(organizator);
        }
    }
}
